### ISSUE TITLE
Looks very interesting - can you share code (snippets)?

### ISSUE THREAD

**Issue by mrgfisher** [dr-mod/online-geiger-counter#1]
Hi!

This looks very interesting, in particular that you've used C. Can you share the code or perhaps snippets of code?

Thanks!

**Comment by dr-mod** [comment]
Hey @mrgfisher , 
Thanks for binning this up, I sort of forgot about this build. I've just uploaded a piece of code that I found that works with the Geiger counter and the display. This one is not optimised and doesn't post the data online.
Hope you find this useful.

**Comment by mrgfisher** [comment]
Thanks!
